AWSTemplateFormatVersion: 2010-09-09
Description: Task Definition

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Project Name Prefix"
        Parameters:
          - PJPrefix
    ParameterLabels:
      Env:
        default: "Environment"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  PJPrefix:
    Type: String
    Default: PJPrefix

  SsmPath:
    Type: String
    Default: SsmPath

  Env:
    Description: Type of this environment.
    Type: String
    Default: dev
    AllowedValues:
      - prd
      - dev

  TaskCpu:
    Type: Number
    Default: 512

  TaskMemory:
    Type: Number
    Default: 1024

  Version:
    Type: String

Resources:
  # ------------------------------------------------------------#
  # CloudWatch LogGroup
  # ------------------------------------------------------------#
  CloudWatchLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "ecs/${Env}-${PJPrefix}-ecs-task"

  # ------------------------------------------------------------#
  # Task Definition
  # ------------------------------------------------------------#
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Env}-${PJPrefix}-ecs-task"
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      ExecutionRoleArn: {'Fn::ImportValue': !Sub "${Env}-${PJPrefix}-ecs-task-execution-role-arn"}
      TaskRoleArn: {'Fn::ImportValue': !Sub "${Env}-${PJPrefix}-ecs-task-role-arn"}
      RuntimePlatform:
        CpuArchitecture: "ARM64"
        OperatingSystemFamily: "LINUX"
      ContainerDefinitions:
        - Name: !Sub "${Env}-${PJPrefix}-container"
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${PJPrefix}:${Version}
          Secrets:
            - Name: ENV
              ValueFrom: !Sub /${SsmPath}/${Env}/ENV
          Environment:
            - Name: TZ
              Value: Asia/Tokyo
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref 'AWS::Region'
              awslogs-group: !Sub "ecs/${Env}-${PJPrefix}-ecs-task"
              awslogs-stream-prefix: ecs
          Essential: true

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  TaskDefinitionArn:
    Value:
      !Ref TaskDefinition
    Export:
      Name: !Sub ${Env}-${PJPrefix}-task-definition
