[package]
name = "rust-hello-world"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
tokio = { version = "*", features =["full"] }
serde_json = "*"
